server:
  port: 8082

spring:
  data:
    mongodb:
      database: workshop
      uri: mongodb://localhost:27017/workshop
      username: root
      password: password
openapi:
  devUrl: http://localhost:8080
#
#springdoc:
#  swagger-ui:
#    path: /workshop-documentation
#  api-docs:
#    path: /workshop-api-docs
#  packages-to-scan: com.michalmlynarczyk.*

token:
  signing:
    key: CgQzZTTsFGWA9nSFPKe+lOalq9lc15jHjxnH0DKxTAA=