server:
  port: 8082
logging:
  level:
    com.michalmlynarczyk: DEBUG

spring:
  application:
    name: WORKSHOP-MANAGEMENT-SERVICE
  data:
    mongodb:
      database: workshop
      username: root
      password: password
      port: 27017
      host: localhost
      authentication-database: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: password

token:
  signing:
    key: CgQzZTTsFGWA9nSFPKe+lOalq9lc15jHjxnH0DKxTAA=

eureka:
  client:
    enabled: false