version: "3.8"

name: bicycle-workshop-management-system
services:
  postgresdb:
    container_name: postgres
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    networks:
      - bike-service-network
    ports:
      - '5432:5432'
    volumes:
      - data:/data/db

  adminer:
    container_name: adminer-bike-service
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - bike-service-network
    ports:
      - '8080:8080'

  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - bike-service-network
    ports:
      - '27017:27017'
    volumes:
      - data:/data/mongo-db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "8079:8081"
    networks:
      - bike-service-network
    environment:
      ME_CONFIG_MONGODB_PORT: '27017'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb

networks:
  bike-service-network:
    driver: bridge

volumes:
  data:
    driver: local
