server:
  port: 8081
logging:
  level:
    com.michalmlynarczyk: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate

#
#springdoc:
#  swagger-ui:
#    path: /workshop-documentation
#  api-docs:
#    path: /workshop-api-docs
#  packages-to-scan: com.michalmlynarczyk.*

token:
  expiration: 1_200_000
  signing:
    key: CgQzZTTsFGWA9nSFPKe+lOalq9lc15jHjxnH0DKxTAA=