server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

token:
  expiration: 1_200_000
  signing:
    key: CgQzZTTsFGWA9nSFPKe+lOalq9lc15jHjxnH0DKxTAA=