server:
  port: 8083
logging:
  level:
    com.michalmlynarczyk: DEBUG

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      database: order
      username: root
      password: password
      port: 27017
      host: localhost
      authentication-database: admin

token:
  signing:
    key: CgQzZTTsFGWA9nSFPKe+lOalq9lc15jHjxnH0DKxTAA=
eureka:
  client:
    enabled: false
