server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<path>.*), /$\{path}
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/authentication/**
          filters:
            - RewritePath=/authentication/(?<path>.*), /$\{path}
        - id: workshop-management-service
          uri: lb://workshop-management-service
          predicates:
            - Path=/workshop/**
          filters:
            - RewritePath=/workshop/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: order
        url: /v3/api-docs/order
      - name: workshop
        url: /v3/api-docs/workshop
      - name: authentication
        url: /v3/api-docs/authentication
management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
